id = "viewtree"
name = "View Tree Syntax Highlighting for $mol"
version = "0.0.3"
schema_version = 1
authors = ["Kirill Novgorodtsev kirrallt@mail.ru"]
description = "Syntax higlighting for view.tree files in $mol web framework"
repository = "https://github.com/dev-cmyser/zed-tree-mol-support"

[grammars.molviewtree]
repository = "https://github.com/Dev-cmyser/tree-sitter-mol-view-tree"
commit = "4796ac4013436acb73c1a36a0537a0b105cd9c2a"
